Add Project 11
mainmeatball/100-javascript-projects pull request #13
Opened 2020-08-01 06:13 UTC by mainmeatball

[Tip Form Project](https://jsbeginners.com/tip-form-javascript-project/)

2020-08-01 06:22 UTC, VagrantAI-c commented on Project 11/index.html
> +					<input id="bill-amount" class="bill-amount">
Инпут можно поставить в `type="number" min="0"` и использовать встроенные валидаторы, используя свойство `valid` элемента, таким образом лишние js-валидаторы можно убрать

https://developer.mozilla.org/en-US/docs/Learn/Forms/Form_validation

2020-08-01 06:25 UTC, VagrantAI-c commented on Project 11/index.html
> +	  				<option>Great - 20%</option>
у option можно указать атрибут value, тем самым без маппинга можно получать значение селекта через `el.value`

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select

2020-08-01 06:32 UTC, VagrantAI-c commented on Project 11/index.js
> +	wrapper.style.height = 'calc(66% + ' + sum + 'px)';
Ненадежно давать расчет высоты на откуп джаваскрипту. Более качественным вариантом будет использовать стаднартные возможности CSS:
- CSSOM подстраивается под event loop, тем самым производя подсчеты в оптимальное для браузера время
- Сильное связывание: высоты твоих элементов могут меняться со временем, но поскольку они декларированы в двух местах (html+css и js), то редактируя что-либо можно забыть поправить одно из мест

2020-08-01 06:41 UTC, VagrantAI-c commented on Project 11/index.css
> +}
Не рекомендуется анимировать высоту по причине сложности ее перерисовки браузеров (т.н. layout thrashing). Если есть возможность, то лучше использовать transform.

https://developers.google.com/web/fundamentals/performance/rendering/avoid-large-complex-layouts-and-layout-thrashing?hl=ru
https://developers.google.com/web/fundamentals/design-and-ux/animations/animations-and-performance?hl=ru

2020-08-01 06:47 UTC, VagrantAI-c commented on Project 11/index.js
> +	return !sumHeight;
Не рекомендуется выполнять в одной функции и сайд эффекты и возвращать значение: если функция чистая, то она должна вернуть значение, если функция выполняет побочные преобразования, то не стоит в ней что-либо возвращать. Как и в других языках - следование паттернам pure и impure функций улучшит архитектуру приложения и его понимание другими людьми, а смешанные функции сложнее отлаживать и тестировать.

2020-08-01 06:54 UTC, VagrantAI-c commented on Project 11/index.js
> +	}, 2000);
Магическое число: непонятно почему именно такое значение, сломается ли что-то если его поменять? Зависит ли оно от чего-то?

2020-08-01 06:55 UTC, VagrantAI-c approved these changes

2020-08-01 12:32 UTC, mainmeatball commented on Project 11/index.js
> +	}, 2000);
Не совсем ясно, что в этом случае делать?
Данное число выбрано для симуляции времени обработки информации, ни с каким данными не связано, несет в себе чисто визуальный эффект.

2020-08-01 15:16 UTC, VagrantAI-c commented on Project 11/index.js
> +	}, 2000);
тогда можно вынести в константу `const UPLOAD_ANIMATION_DURATION = 2000;`

2020-08-01 16:04 UTC, VagrantAI-c commented on Project 11/index.html
> +					<input id="bill-amount" class="bill-amount">
Валидация с помощью JS: https://developer.mozilla.org/en-US/docs/Web/API/Constraint_validation

2020-08-02 11:46 UTC, VagrantAI-c commented on Project 11/index.js
> +	return validAmount && validPeople && validTip;
Здесь не нужна стратегия, если есть необходимость сделать действие над всеми элементами. Стратегия позволяет выбрать конкретный сценарий при наличии нескольких возможных, но он нивелируется тем, что вызывается несколько раз подряд с разными значениями. Также аналогично возникает проблема что функция validate ни pure ни impure, а смешанная. Проверку следует вынести в свою функцию, а эффект в другую, например:
```javascript
const elementsAreValid = [el1, el2, el3].all(el => el.checkValidity());
[el1, el2, el3].forEach(el => assignVisibility(el));
```

2020-08-02 11:51 UTC, VagrantAI-c commented on Project 11/index.html
> +	  				<option value="1">Great - 20%</option>
Смысл value нивелируется если его все равно придется конвертировать из констант во что-то. Можно сразу назначить цифровые значения и в коде кастить ее к цифре.

2020-08-02 14:02 UTC, VagrantAI-c commented on Project 11/index.js
> +class InputEntity {
Одобряю такой подход с инкапсуляцией

2020-08-02 14:03 UTC, VagrantAI-c commented on Project 11/index.js
> +			: (
лучше избегать операторов группировки стейтментов, они как правило ухудшают читаемость. Фигурные скобки как раз лучше использоваться в подобных сценариях.

2020-08-02 14:03 UTC, VagrantAI-c commented on Project 11/index.js
> +	return [billAmount, personNumber, tipPercent].every(el => el.isValid());
Можно вынести массив с инпутами в переменную, раз он используется в нескольких местах

2020-08-02 14:05 UTC, VagrantAI-c commented on Project 11/index.js
> +		el.isValid()
продолжая подход с инкапсуляцией - эту функцию можно вынести в созданный класс

2020-08-02 14:06 UTC, mainmeatball commented on Project 11/index.js
> +	return validAmount && validPeople && validTip;
Только походу там не `[].all()`, а `[].every()`.

2020-08-02 14:06 UTC, VagrantAI-c requested changes
Одобряю такой подход с инкапсуляцией, но если реализовывать его полностью - то остается еще момент где можно его дожать

2020-08-02 14:40 UTC, VagrantAI-c approved these changes
Это уже достойный код, сложно придумать с ним что-то еще

2020-08-02 14:40 UTC, VagrantAI-c commented on Project 11/index.js
> +const calculateButton = $('#calculate-button')[0];
неиспользуемый филд

2020-08-02 21:22 UTC, merged