Add Project 12
mainmeatball/100-javascript-projects pull request #14
Opened 2020-08-02 11:53 UTC by mainmeatball

[To Do List Project](https://jsbeginners.com/todo-list-javascript-project-v1/)

2020-08-02 12:02 UTC, VagrantAI-c commented on Project 12/index.js
> +	if (duplicate(input.value)) {
Чистые функции которые возвращают булеан следует по аналогии с филдами именовать начиная с is/are/should (в рамках имплементации самодокументируемой функции)

2020-08-02 12:05 UTC, VagrantAI-c commented on Project 12/index.js
> +	const elementNameParagraph = event.target.parentNode.parentNode.parentNode.querySelector('#todo-el-name');
Ориентироваться на уровень вложенности ненадежно в силу изменчивости (с течением времени) дом структуры. Этот селектор не равен `document.getElementById('todo-el-name')`?

2020-08-02 12:11 UTC, VagrantAI-c commented on Project 12/index.js
> +	el.classList.contains('checked') ? el.classList.remove('checked') : el.classList.add('checked');
```suggestion
	el.classList.toggle('checked');
```
https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList/toggle

2020-08-02 12:16 UTC, VagrantAI-c commented on Project 12/index.js
> +	elementNameParagraph.setAttribute('contentEditable', 'true');
Чем обусловлено наличие contentEditable элемента заместо более стандартного и доступного инпута?

2020-08-02 12:19 UTC, VagrantAI-c requested changes
Помимо перечисленного, имеется один архитектурный момент в разметке: чем делать инпут (контент эдитабл) в каждом темплейте - его можно вынести в отдельный элемент и чистить его вэлью при каждом добавлении. Преимущество такого подхода:
- семантически данный контрол не принадлежит темплейту, который отвечает за добавленные сущности
- если сделать добавление через сабмит формы, то можно не сбрасывая фокуса с инпута добавлять новые элементы вводя данные и нажимая энтер

2020-08-02 14:46 UTC, mainmeatball commented on Project 12/index.js
> +	const elementNameParagraph = event.target.parentNode.parentNode.parentNode.querySelector('#todo-el-name');
> Этот селектор не равен document.getElementById('todo-el-name')?

Не совсем. Таким образом я получаю `paragraph`, который относится исключительно к `div`'у, в котором был произведено нажатие на кнопку.
Каким образом можно иначе получить элемент, который находится в контейнере, содержащем кнопку, на которую кликнули? Возможно, его можно передать как-то из HTML?

2020-08-02 14:54 UTC, VagrantAI-c commented on Project 12/index.js
> +	const elementNameParagraph = event.target.parentNode.parentNode.parentNode.querySelector('#todo-el-name');
у тебя несколько элементов с айди todo-el-name?

2020-08-02 14:56 UTC, mainmeatball commented on Project 12/index.js
> +	const elementNameParagraph = event.target.parentNode.parentNode.parentNode.querySelector('#todo-el-name');
Каждый элемент - это как раз и есть этот `todo-el-name`.

![image](https://user-images.githubusercontent.com/25621191/89125757-5a8ed500-d4e9-11ea-9aea-4745938abae9.png)

2020-08-02 14:57 UTC, VagrantAI-c commented on Project 12/index.js
> +	const elementNameParagraph = event.target.parentNode.parentNode.parentNode.querySelector('#todo-el-name');
в таком случае это некорректный подход, только один уникальный айди имеет право быть в доме, в противном случае нивелируется весь принцип айди атрибута, хоть это и валидно с точки зрения хтмл5

2020-08-02 21:27 UTC, VagrantAI-c requested changes
Направление корректное и реализация идет в нужную сторону, что крайне хорошо

2020-08-02 21:27 UTC, VagrantAI-c commented on Project 12/index.js
> +		Array.from(this.todoList.querySelectorAll('.todo-el')).forEach(el => el.remove());
`addEventListener` создает слушатель, который не разрушается при дестрое элемента, его надо подчищать вручную с помощью коллбэка, который он возвращает, в противном случае он может создать утечку памяти. В идеале сделать дестрой функцию в `TodoElement`, чтобы она сама и уничтожала себя и терла свои листенеры.

2020-08-02 21:27 UTC, VagrantAI-c commented on Project 12/index.js
> +		this.todoList.appendChild(todoElement.domElement);
Раз есть возможность регулировать `TodoElement`ы, то можно регулировать инстансы класса, нежели дом элементы напрямую. В противном случае выходит что за дом узлы туду элемента отвечают два разных класса.

2020-08-02 21:27 UTC, VagrantAI-c commented on Project 12/index.js
> +
Все ли поля выше используются? Возможно стоит подчистить лишние.

2020-08-03 18:58 UTC, VagrantAI-c commented on Project 12/index.js
> +		this.nameInput.readOnly = true;
есть ли разница между атрибутом disabled и readonly пропертью? Почему было выбрано последнее?

2020-08-03 18:59 UTC, mainmeatball commented on Project 12/index.js
> +		this.nameInput.readOnly = true;
Есть. `Disabled` визуально помечает `input` поле как нередактируемое (придает ему серый цвет).
`Readonly` же убирает только возможность редактировать поле, не меняя его визуально.

2020-08-03 19:01 UTC, VagrantAI-c commented on Project 12/index.js
> +		this.nameInput.readOnly = true;
нередактируемый инпут должен визуально об этом сообщать пользователю, иные сценарии должны иметь веское обоснование для такого поведения

2020-08-03 19:07 UTC, mainmeatball commented on Project 12/index.js
> +		this.nameInput.readOnly = true;
Данное поле выбрано инпутом лишь для добавления возможности редактировать его и помещать курсор в конец при фокусировке. На деле это наименование `todo item`'а. Визуально оно никак не отличается от обычного `p` элемента, и будет странно, если оно всегда будет выделено как `disabled`. Если пользователь захочет отредактировать наименование, он нажмет на кнопку `edit` и автоматически фокус поместится на данный `input` элемент.

2020-08-03 19:12 UTC, VagrantAI-c commented on Project 12/index.js
> +		this.nameInput.readOnly = true;
в таком случае семантически было бы корректнее менять динамически спан на инпут в случае нажатия на кнопку "редактировать", но в целях облегчения кодовой базы можно оставить и в таком виде.

2020-08-03 19:22 UTC, VagrantAI-c requested changes

2020-08-03 19:22 UTC, VagrantAI-c commented on Project 12/index.js
> +function addItem(event) {
Если у тебя имеется Page класс, который управляет логикой страницы, то почему бы не перенести оставшиеся методы туда?

2020-08-03 19:22 UTC, VagrantAI-c commented on Project 12/index.js
> +		return name in todoElementMap;
Поскольку имя в туду классе имеет динамическую структуру, будет качественнее вести массив туду инстансов и чекать через `Array.some` на наличие данного имени

2020-08-03 19:22 UTC, VagrantAI-c commented on Project 12/index.js
> +		this.removeButton.addEventListener('click', this.boundRemoveButtonListenerCallback);
В качестве высшего пилотажа могу предложить следующую структуру листенеров: поскольку имеется несколько листенеров и они используются в нескольких местах (addEventListener и removeEventListener), при изменении чего-либо есть шанс упустить что-то аналогичное в ином месте. Можно реализовать метод с апи `addListener(name, boundCallback)` который будет инициализировать листенер и добавлять его в массив листенеров в стейте инстанса класса. При дестрое зачищать представленные листенеры в цикле. Возможно понадобится дополнительный класс.

2020-08-03 19:27 UTC, VagrantAI-c commented on Project 12/index.js
> +		return todoElements.some(el => el.getName() == name);
```suggestion
		return todoElements.some(el => el.getName() === name);
```

2020-08-03 19:27 UTC, VagrantAI-c commented on Project 12/index.js
> +		todoElements = todoElements.filter(el => el == this);
```suggestion
		todoElements = todoElements.filter(el => el === this);
```

2020-08-03 19:30 UTC, VagrantAI-c commented on Project 12/index.js
> +		todoElements = todoElements.filter(el => el == this);
Если требуются такие операции, то лучше использовать `Set`, нежели переназначать массив. Переназначение массива является не слишком хорошей практикой поскольку имеет множество мутирующих свойств в себе, которые можно использовать (типа `splice`). В добавок ему можно будет дать const, что всегда предпочтительнее.

2020-08-03 19:34 UTC, VagrantAI-c commented on Project 12/index.js
> +		todoElements = todoElements.filter(el => el == this);
Данный массив можно будет инкапсулировать в класс Page. Не очень хорошо когда над глобальным стейтом работают сразу несколько классов.

2020-08-03 19:44 UTC, VagrantAI-c commented on Project 12/index.js
> +		const todoElement = new TodoElement(page.template.content.cloneNode(true));
```suggestion
		const todoElement = new TodoElement(this.template.content.cloneNode(true));
```

2020-08-03 20:22 UTC, VagrantAI-c commented on Project 12/index.js
> +		this.listeners = [new ElementListener(this.nameInput, 'focusout', this.boundInputListenerCallback),
Короче будет сразу написать `this.fn.bind(this);` вместо выноса функции в константу.

Выравнивание инициализатора массива производится следующим образом, если в ряд все константы не помещаются:
```javascript
const a = [
  1,
  2,
  3,
];
```

2020-08-03 20:22 UTC, VagrantAI-c approved these changes

2020-08-03 20:34 UTC, merged