Add Project 14
mainmeatball/100-javascript-projects pull request #20
Opened 2020-08-09 20:30 UTC by mainmeatball

[Grocery List Local Storage Project](https://jsbeginners.com/javascript-grocery-list-project/)

2020-08-09 21:31 UTC, VagrantAI-c requested changes
- анимации основанные на смене цвета и бэкграунда одновременно смотрятся неорганично поскольку имеются такие промежуточные состояния, при которых кнопка теряет читаемость 
- не стал прописывать все места отсутствия `readonly`, указал лишь одно из мест
- имеются неконсистентные return types: void должен либо присутствовать во всех подобных функциях, либо отсутствовать
- некоторые функции можно поместить в приватную область видимости
- некоторые функции вызываются лишь из одного места и недостаточно комплексные чтобы иметь возможность своего существования: их можно просто заинлайнить в местах использования

2020-08-09 21:31 UTC, VagrantAI-c commented on Project 14/service/grocery.service.ts
> +    private groceryList = select(AppElement.GROCERY_LIST);
readonly?

2020-08-09 21:31 UTC, VagrantAI-c commented on Project 14/entity/grocery-item.component.ts
> +            select(AppElement.GROCERY_ITEM_REMOVE_BUTTON, template) as HTMLButtonElement,
можно добавить оверрайд декларацию в select чтобы этот AppElement возвращал HTMLButtonElement и тогда можно будет не кастовать

2020-08-09 21:31 UTC, VagrantAI-c commented on Project 14/entity/grocery-item.component.ts
> +            this.boundLocalStorageFn(this);
```suggestion
            this.boundLocalStorageFn?.(this);
```
и проверку можно будет убрать

2020-08-09 21:31 UTC, VagrantAI-c commented on Project 14/index.html
> +			<button type="submit" class="button">New Item</button>
```suggestion
			<button type="submit" class="button">Add item</button>
```
Кнопки называются либо глаголом, либо глагол + сабжект к которому относится действие

2020-08-09 21:31 UTC, VagrantAI-c commented on Project 14/helper/grocery-storage.handler.ts
> +    public addItem(item: NameAware) {
необязательно употреблять сабжект в названии функций, когда название класса уже определяет с какой сущностью будет работать данный сторейдж. Исключение может составлять редкие сценарии в духе get - непонятно что оно вернет, одну или несколько сущностей.

Тоже самое касается и остальных сущностей.

2020-08-09 21:31 UTC, VagrantAI-c commented on Project 14/helper/grocery-storage.handler.ts
> +        groceryList.splice(itemIndex, 1);
такая конструкция уничтожит почти весь массив, если индекс будет -1 (то бишь findIndex не нашел искомое значение)

2020-08-09 21:31 UTC, VagrantAI-c commented on Project 14/entity/grocery-item.component.ts
> +    public bind(removeFromLocalStorageFn: Callback<GroceryItemComponent>): void {
- стоит избегать названий, которые могут конфликтовать с браузерным апи или когнитивно искажать восприятие: можно мисинтерпретировать назначение функции перепутав или сравнив ее с `Function.bind()`
- не стоит делать сильную связь путем привязки названия коллбэка к определенной функции в иной сущности. Не важно кто будет слушателем на том конце или что будет выполнять коллбэк, важно лишь то что он будет вызван. Следует называть коллбэк коллбэком: если рассматривать данный класс как изолированный, то он не может знать что будет делать прокинутый сюда коллбэк.

2020-08-09 21:31 UTC, VagrantAI-c commented on Project 14/service/grocery.service.ts
> +    public renderItems(...items: GroceryItemComponent[]): void {
```suggestion
    private renderItems(items: GroceryItemComponent[]): void {
```

2020-08-09 21:31 UTC, VagrantAI-c commented on Project 14/service/grocery.service.ts
> +        this.renderItems(...localStorageItems);
```suggestion
        this.renderItems(localStorageItems);
```

2020-08-10 06:57 UTC, mainmeatball commented on Project 14/entity/grocery-item.component.ts
> +            this.boundLocalStorageFn(this);
Можно даже без null-check, так как добавил default value, инициализируя переменную.

2020-08-10 06:58 UTC, mainmeatball commented on Project 14/helper/grocery-storage.handler.ts
> +        groceryList.splice(itemIndex, 1);
Добавил проверку на -1 (throw new Error)

2020-08-10 11:19 UTC, VagrantAI-c requested changes
Иимеются неконсистентные return types: void должен либо присутствовать во всех подобных функциях, либо отсутствовать. Чтобы таких ситуаций не возникало, надо будет поставить линтер.

2020-08-10 11:19 UTC, VagrantAI-c commented on Project 14/entity/grocery-item.component.ts
> +    private constructor(private name: HTMLElement,
Чем делать неявные структуры со статическими функциями и приватным конструктором: имеются все возможности сделать просто конструктор с необходимыми аргументами
```typescript
constructor(private name: string) { ... }
```

Статические же функции редко где имеют свое применение в реальной жизни, одним из примеров может быть билдер паттерн, который к этому сценарию не подходит. Другим примером является необходимость создать альтернативный конструктор, который никак нельзя реализовать через существующий, но в данном случае имеется лишь функция of, которая дергает приватную функцию ofTemplate, которая дергает приватный конструктор. Альтернатив тут быть не может, поэтому все хорошо сокращается бритвой Оккама до обычного конструктора.

2020-08-10 11:19 UTC, VagrantAI-c commented on Project 14/entity/grocery-item.component.ts
> +                        public domElement: HTMLElement) {
Необходимо решить принадлежность данного элемента: либо она находится в паблик апи и управляется извне, либо в прайват апи и инкапсулирует функции для своего управления изнутри (функция remove). Предпочтение в таких ситуациях должно отдаваться последнему. Не стоит давать знать наружу что этот класс располагает какими-то дом узлами и экспозить их - в этом и суть создания данного класса, в противном случае мы могли бы делать все в глобальных функциях.

2020-08-10 11:19 UTC, VagrantAI-c commented on Project 14/entity/grocery-item.component.ts
> +        this.removeButton.removeEventListener('click', this.boundRemoveButtonFn);
Подобные функции-ванлайнеры можно заинлайнить в местах использования, тем более что это место - одно.

2020-08-10 11:19 UTC, VagrantAI-c commented on Project 14/helper/grocery-storage.handler.ts
> +            throw new Error(`Expected "${item.getName()}" to be present in local storage`);
Кидать ошибку при отсутствии энтри было бы некорректно по той причине, что сущности могут быть выселены в любой момент без участия кода. Кого тогда будет винить эта ошибка если не самого себя? Тут бы больше подошел метод fault tolerance, когда отсутствующая сущность будет просто игнорироваться. Да, локал сторейдж может подвести, но это не повод скидывать ошибку на юзера и не давать ему воспользоваться задуманным функционалом.

2020-08-10 11:19 UTC, VagrantAI-c commented on Project 14/service/grocery.service.ts
> +    public add(name: string): void {
Эта функция имеет дублируемый функционал с предыдущей. Часть функционала легитимно выносится в `render()`. Семантически будет две фазы: создание класса и его рендер. Если бы за создание и рендер отвечал `GroceryItemComponent` (что предпочтительнее: данный класс должен сам знать как себя зарендерить, если ему предоставят необходимый дом-контейнер), то такой подход назывался бы двухфазный конструктор.

2020-08-10 20:19 UTC, VagrantAI-c approved these changes
g2g

2020-08-10 20:33 UTC, merged